language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
script:
  - npm run test:unit
deploy:
  provider: heroku
  app: tranquil-mountain-27886
  api_key:
    secure: kwIcK8cC6TX8sBd+VukKCJCmoky4kwtsvCm3A4oSKXjbDguMdxdPSB2IeNXugxcCsbDMm2rTdyS9tEPlZQkAXhmC7mXheGviFjp0yYWomFT4FqAWO+C7BV9aMRkeOBxCCsUlGZ/xenqXr6CGT7nJhDyAykMLNfXSgnpNi1f2aJTOPK2+AD9tIA44CIh9tVWt0NoA4HiEzWXTv2TaXoZ1RLKi/8niYTgqyH1Nr5YLisPrPHATRS/WmAo/nMQ9I0fcKAkR5iAPf24NQf2cVREr/1N+XKWELgII87UKOjigbaq4we9yznbuaAmj2klWQKUOiQ3vmxPfJmLu4K1Dt3z+9LLL3TGOqQiS3+gRD2GgpJZfRAKStF+nUZgCpB8xViwmRr0kvHwZvkyAssjvcUyGmO63AkWkbmo03eMTAXuwyqRrRsvRLqvlShNMdTTUI4hnhgYv9n+9B6UA414U3GPoN58Mo/2ACXwerc4Tdcm+AjE0C4vnSYJOyLBXWhlIWg1TMcedd23jLpPI5ksZah7ShWzFbV2q/czfXyDFb2e6EufdaztyZuNywbhF6vn0h5JEdgmoF7iWK0RLwIiDKXxHjQxc4qucEgG/WcSYfJYUh4DFR1CcdN+qoRmNB5TPxvMMxQSLniqS/EeptY3jsguPgOUZNUqlSVU6c/7O8Tqqjdc=
