language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
script:
- npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: Vy9dbZ2nqwY1/aTzANCaEbBrxSJi07wCY3g5QYd5+xX0LDqj0Efuz/oxI3xvPO23JdxjF1w48HJbb2zk1yeSMtGgYU68z2sVk/yt6VVtlSQ33nLUYPMLweDncdyp/s0oYGog8WOxnDyoBhgCSM6cp2FRKXeFwM91sQ1ogleKhjJuSsqKk0D0z906xKH1sgh4Rj0iRjVIHWG5lfJ6aLA4Q3hSLgeaxnYtjxut/L8gAPEBItISkx4RBRsUMV4PX8CZwN67hH9D26Yc/CZgoAGohup74zL2gbMsw+0Y7RL3+bSljZMahEnmoib0lbGSlgRgwclt+86NygJqj5inFA/8WAYqMcgQ3skmr4RE6CSvoydirCjPOpxtsqe07Ql6dIY4liMbo260v3miWSn+aqjIeNghC8WtTvxVvfLR/zcz18N2AEpePfKuXqhwULQAN+KwQIOMJ0Ii3IQZIN/Q03LaSdPg1ivN19VKBTatDUVH/9YWuV/5DuyB13/IupLp5ncYAmx0x+JmP8+SWjY/k2y5tmzOSB320/WWoB9EUO3X5Q51mDFWjap7R9kELbfh+0eU2TIQOnV4iJG/rS5DhIvdX4P+WFklxIcJDz0GniUgQ0qa7zzpwiYlocH4wB6g+VT8CNFvdmuahMkj2Up0i4kVpxk/lJnmJBo9qm+FTvBB3us=
env:
  global:
    secure: Vy9dbZ2nqwY1/aTzANCaEbBrxSJi07wCY3g5QYd5+xX0LDqj0Efuz/oxI3xvPO23JdxjF1w48HJbb2zk1yeSMtGgYU68z2sVk/yt6VVtlSQ33nLUYPMLweDncdyp/s0oYGog8WOxnDyoBhgCSM6cp2FRKXeFwM91sQ1ogleKhjJuSsqKk0D0z906xKH1sgh4Rj0iRjVIHWG5lfJ6aLA4Q3hSLgeaxnYtjxut/L8gAPEBItISkx4RBRsUMV4PX8CZwN67hH9D26Yc/CZgoAGohup74zL2gbMsw+0Y7RL3+bSljZMahEnmoib0lbGSlgRgwclt+86NygJqj5inFA/8WAYqMcgQ3skmr4RE6CSvoydirCjPOpxtsqe07Ql6dIY4liMbo260v3miWSn+aqjIeNghC8WtTvxVvfLR/zcz18N2AEpePfKuXqhwULQAN+KwQIOMJ0Ii3IQZIN/Q03LaSdPg1ivN19VKBTatDUVH/9YWuV/5DuyB13/IupLp5ncYAmx0x+JmP8+SWjY/k2y5tmzOSB320/WWoB9EUO3X5Q51mDFWjap7R9kELbfh+0eU2TIQOnV4iJG/rS5DhIvdX4P+WFklxIcJDz0GniUgQ0qa7zzpwiYlocH4wB6g+VT8CNFvdmuahMkj2Up0i4kVpxk/lJnmJBo9qm+FTvBB3us=
