language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
script:
- npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: nbboYllf0hpOyDq5UZt3Kzw0MDMqmpmBu2g6BK7s59KtJ9GtsPn6G6FtBTU0u8TePe2LUXbYkDmjlJ3M6IbhCA8rTMy8m+6pljsHKwXtOyVmWSS2LXeoaCbptmmtcaC4lpPtj6S/OpQzCbJAb3eK36MtQLCmLViwleYuxvyuWR9jGSDwcndnJ43Dt08KWVtD611uZZgmNH7uEz0arx1ZslZC/Hl2gMow37PFeP9Qod9Ey4LJ0np0gyZrCzYKbBpm9YsYUzlfqNyFU7P5hZMLEyiSg0iCUmJk3G8Oz2j5pExWiis32SIMCDWWnccGQVf4W01w7OJAYAVLFF2QoZindO8bk69b9RzxORAX7f+m0+VMFzf+syO1MecEAI4u0j//bmWjGM0ci4ht3u5P08NM86QDoZWFqwsc4hHCUFll/BdLcBUulJhvxIl2CymO2SzeliIMoetWwOveDZQnYU7hQsJaVHQ6O1N8bA7n2rjvSwUY/HKiYTHALX0StElg+LckIsHlS7qZMiEXoKd8sxDf0BhzeA+DBk9PdGJvDEIu6RYyv64cKXFUcTGCX4WbrxsMW0/OTc2iiCJFzv3Vp7Q74KUb2ePQyhFJZf9Iq/rQ5TqEgNpb/gQ0DmC00oOAhLdxC5rWFyk4Fw5YAgmHG/cbPNXz3QQ0HOWb3x9WuesVZY4=
