language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
script:
- npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: nWXDyov8ivjKJqB7ZlNpKVcg3CeNKsEnCXM9HtQ3uor2NWGCk0zPQhldJQ4WBeVnZttPvactXWgNsAitKdDGg3AGuBZvH/pialyg/YsRDJ5AaVRN3C2XqDRXrBWzwgb7GbOdVUfcu9iwqjbDFebxS6AZ04FhxE2dX0/MfisfrT+0wuHTg7FiciIhbx8e9LEp9VOXnxyioNqj2YNwl5tQP4Wpsey6yEN7jcrUuohCzQBRhd4ps+7S6L3xHRJgiVCOuCg1BbjdTzgeltRBY4tE6wsW/QuYoVKrTLPyidS8rIlB4GHj/PgMEqSX/vsZYYovDbCJMRa0Gx+AGqNnmplyIByTy8KT2czCzhZ37/dD8dXjz0aR4629a1haMrfeKDuE73B6Wj3XTHOnU0jpdnI1SpaeSYTCdFtaESqhPtOqPCJ/EL8OIkdkX+bnDKThrYRKjpd3P0umU1UfOY/oXnCaAqJv8IhQHYCCdjw1OKoyx/+TnhBJHLTcKA0wSWoX/D45deBpaiYtShExNMq0oSYo/GD3L4/1P9Ra7leXiVDjspT/lA38MGFn/LiYebg/8DAR/iHNC0KR0k20QMRAbeRfLxnRDSVKMgeU+7aX4RSppqfudDQerGhwenQv/wu6R/78ZAMY8a2JugdFatdz2V1cCcv6SasreqzT34ckfv6z4K0=
