language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: "RLg93QuR2RnPi9y4I7YccnoucoYhLDtvzOcKWarSsUr3ZsJefBguajtXoVMqpvXaUxei1fh5LmVFUdrutXnd+bKP6W0C6bmHMVtQ6UJhU1TmdhohsEeQgik2hSb3GlCIFLiyYTUpJqvVbPpttQ2z4S3RJGX0BB5zz8t5RMqQOuoisxaScBU1EvdUgwzzWC9ZBL83LCfQaZIZQtn7eerbKG4x4AVBw2Gza87aIOkiMdhgqiL1GvPzME7mIVP0KK9rOzjYayblgO+u5TsuMSWP8nd6dxzCei9Z6vR6EAdsF+p5ctqGiOR0gFOaZVOCwH1KcHKMwY3yPZEMkkU63Txwc3NBoL0lKpjOxiuB4vos/ABa6OYGoXXusrlgwDg4nSe8+gXTEQvZOCiRewRf/2/PUme7mA9iXQrCbsvjyQNcHQSf+Iw1fWUCtUTRlNsK6geAOMX3pO4QUyfEfjcORJY7cMNOk3mO4r4xLfU1MgnlCMsRGmxCAmh89g/yIT+gEUNgSKQUnx0Qvian2nQsw2T9wytMSxfUIRyaBAeumoO1BZS6NYFOzAzLFGQJ65HgMxqKQqUAwT0IdYm1eH/w9jE+kVbIYX67WpRxmMi9xctBifGXj8l2pgFkPW/2kdkRCDi6sYaybF3mY07z1u/8K7DtvchgDQhiGJ5gdPRI6C2f0ZI="
